_target_: src.systems.autoencoder.AutoEncoder
model_ae: ${models.autoencoder}
model_d: ${models.discriminator}
lpips: ${models.perceptual}
loss_weights:
  reconst: 10.0
  internal: 1.0
  perceptual: 1.0
  adversarial: 0.1
d_loss_weight: 0.1
lr_g: 0.0005
lr_d: 0.0005
betas_g: [0.9, 0.999]
betas_d: [0.9, 0.999]
