_target_: src.systems.autoencoder.AutoEncoder
model_ae: ${models.autoencoder}
model_d: ${models.discriminator}
lpips: ${models.perceptual}
loss_weights:
  reconst: 2.0
  internal: 1.0
  perceptual: 1.0
  adversarial: 0.5
d_loss_weight: 0.5
lr_g: 0.0001
lr_d: 0.0001
betas_g: [0.9, 0.999]
betas_d: [0.9, 0.999]
