_target_: src.models.vqvae.VQVAE
embedding_dim: 4
num_embeddings: 8192
beta: 0.25
im_channels: 3
down_channels: [64, 128, 256, 256]
mid_channels: [256, 256]
downsamples: [True, True, True]
down_attn: [False, False, True]
num_heads: 4
num_down_layers: 2
num_mid_layers: 2
num_up_layers: 2
