defaults:
  - /callbacks@best_checkpoints: model_checkpoint
  - /callbacks@last_checkpoints: model_checkpoint
  - _self_

best_checkpoints:
  monitor: "Validation/percep_recon_loss"
  mode: "min"
  save_top_k: 3
  filename: "model-{epoch:02d}-{percep_recon_loss:.2f}"
  dirpath: "checkpoints/best_models/"

last_checkpoints:
  monitor: "epoch"
  mode: "max"
  save_top_k: 1
  filename: "model-{epoch:02d}-last"
  dirpath: "checkpoints/last_models/"
