defaults:
  - models/autoencoder: vqvae
  - models/discriminator: patch_gan
  - models/perceptual: lpips
  - loggers: default
  - strategy: ddp
  - callbacks: default
  - systems: AutoEncoder
  - datamodule: celebahq-resized
  - trainer: default
  - sweep: null
  - _self_

loggers:
  wandb:
    project: "AE Test 256x256"

datamodule:
  num_workers: 16

sweep_agent_count: 50
