defaults:
  - models/autoencoder: vqvae
  - models/discriminator: patch_gan
  - models/perceptual: lpips
  - models/diffusion: u-net
  - noise_scheduler: linear
  - loggers: default
  - callbacks: default
  - strategy: ddp
  - systems@autoencoder: AutoEncoder
  - systems@ddpm: ddpm
  - datamodule: celebahq-resized
  - trainer: default
  - _self_

## USED AUTOENCODER CONFIGURATION
models:
  autoencoder:
    beta: 0.6443345881327225
    down_channels: [32, 64, 128, 256]
    embedding_dim: 5
    num_embeddings: 4014
    num_down_layers: 1
    num_mid_layers: 4
    num_up_layers: 2
    num_heads: 4
  discriminator:
    conv_channels: [64, 128, 256]
  diffusion:
    in_channels: 5
    out_channels: 5

callbacks:
  best_checkpoints:
    monitor: "Validation/Loss-ddpm"

loggers:
  wandb:
    project: "DDPM Test 128x128"

datamodule:
  batch_size: 32
  num_workers: 4
  pin_memory: true

ae_checkpoint: null # "<team-name>/<project-name>/<model-name>:v<version-number>"
checkpoint: null # "<team-name>/<project-name>/<model-name>:v<version-number>"
