defaults:
  - models/autoencoder: vqvae
  - models/discriminator: patch_gan
  - models/perceptual: lpips
  - models/diffusion: u-net
  - noise_scheduler: linear
  - loggers: default
  - callbacks: default
  - strategy: ddp
  - systems@autoencoder: AutoEncoder
  - systems@ddpm: ddpm
  - datamodule: celebahq-resized
  - trainer: default
  - _self_

autoencoder_weights: ""

callbacks:
  best_checkpoints:
    monitor: "Validation/Loss-ddpm"
