__target__: lightning.pytorch.callbacks.ModelCheckpoint
monitor: "Validation/Loss-weighted-average"
mode: "min"
save_top_k: 3
filename: "model-epoch{epoch:02d}-val_loss{Validation/Loss-weighted-average:.2f}"
dirpath: "checkpoints/best_val_loss_models/"
