name: sweep_ddpm
method: bayes
metric:
  name: "Validation/Loss-ddpm"
  goal: minimize

parameters:
  ddpm.model_diffusion.t_emb_dim:
    distribution: int_uniform
    min: 128
    max: 1024
  ddpm.noise_scheduler.num_timesteps:
    distribution: int_uniform
    min: 500
    max: 3000
  ddpm.noise_scheduler.beta_start:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-3
  ddpm.noise_scheduler.beta_end:
    distribution: log_uniform_values
    min: 1e-3
    max: 1e-1
  ddpm.lr:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-3
  datamodule.batch_size:
    distribution: int_uniform
    min: 16
    max: 128

early_terminate:
  type: "hyperband"
  min_iter: 2
