program: train_ddpm.py
name: sweeptest
method: bayes
metric:
  name: "Validation/Loss-ddpm"
  goal: minimize
parameters:
  diffusion_steps:
    values: [1000, 2000, 3000]
  learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-3
  batch_size:
    values: [16, 32, 64]
  weight_decay:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-2
early_terminate:
  type: hyperband
  min_iter: 1
  max_iter: 100
  reduction_factor: 3
  grace_period: 5
  s: 0.01
  eta: 3
